### ISSUE TITLE
Captions are not automatically read by screen readers when they appear/change

### ISSUE THREAD

**Issue by cannona** [paypal/accessible-html5-video-player#111]
On the element which holds the captions, add the following attributes:

* aria-live="polite"
* aria-atomic="true"

I'd be happy to help test this with both Jaws and NVDA.

**Comment by hozefaj** [comment]
@cannona You want to send a PR with the updated code?

**Comment by weboverhauls** [comment]
I don't believe this is necessary. A screen reader user can already hear the audio described in the captions.

**Comment by cannona** [comment]
@weboverhauls, while you are correct that the screen reader user can read captions upon request, this requires that screen reader users continuously request that this section be read, in order to know if there have been any updates. 

It basically turns into a game of "Is there a new caption yet?"

"How about now?"

"Ok, now?"

"Anything yet?"

On the other hand, with this change I'm proposing, screen readers will automatically read the captions as they appear, which they ordinarily won't do.

**Comment by cannona** [comment]
@hozefaj, I'll try to grab some time in the next couple days to do so.

**Comment by weboverhauls** [comment]
I am closing this issue. Sorry, but the bad (hearing captions and the audio at same time) outweighs the good (knowing if captions are shown). Again, a screen reader user can already hear the audio that's being described in the captions and can assume the captions are functioning correctly.

**Comment by cannona** [comment]
A couple points @weboverhauls: It's not about knowing if captions are displayed, or knowing whether they are functioning. It's about being able to hear the captions read by the screen reader if one wants, or see them on a braille display. A deafblind user, for example, would be seriously disadvantaged by not having them shown on their display as they appear. If the captions are interfering with a screen reader, then the user has the option to turn them off, just as a sighted user can turn them off should they find them distracting.

I would also point out that this behavior is not unique. The Youtube video player also causes screen readers to automatically read the captions as they appear. This has proven very valuable when, for example, the captions contain language translations.

**Comment by weboverhauls** [comment]
Good points. If a screen reader user is able to turn off the captions entirely, then I'm OK with this. Thank you.

**Comment by cannona** [comment]
Yes. In the code I submitted, when the captions are disabled, they are not read by the screen reader, as aria-live is set to off, and the element is hidden from everyone, including screen readers. In addition, the checkbox for the captions is easily located and toggled with a screen reader (tested in Chrome with Jaws).
