### ISSUE TITLE
deprecate bower?

### ISSUE THREAD

**Issue by mreinstein** [paypal/accessible-html5-video-player#113]
bower is on the decline, and we're already in npm. In fact they recommend switching:

https://bower.io/blog/2017/how-to-migrate-away-from-bower/

 Should we drop bower support in favor of simplicity?

**Comment by mreinstein** [comment]
happy to submit a PR for this if it is helpful

**Comment by hozefaj** [comment]
Yeah I kinda agree that bower is no longer used. I have not seen it been recently in any project. I guess we can remove it to simplify the code. @mreinstein will accept the PR removing bower support.
