### ISSUE TITLE
why does docs/ have duplicate versions of css and js?

### ISSUE THREAD

**Issue by mreinstein** [paypal/accessible-html5-video-player#114]
it seems that `docs/css/` and `docs/js/` are duplicates of `css/` and `js/`.

Does it make sense to symlink one of them so we have 1 copy? Happy to submit a PR for this

**Comment by hozefaj** [comment]
Yes please. Go for it. Thanks.

**Comment by mreinstein** [comment]
@hozefaj I created a PR for symlinking `px-video.js`, but I noticed that the `docs/css/px-video.css` is very different from `css/px-video.css`  (384 lines vs 318.)  Any idea why these css files are so different?

**Comment by mreinstein** [comment]
Ignore my last comment. For some reason my text editor was doing weird things. The css files are identical. I've verified this with:

```bash
git diff --no-index js/px-video.js docs/js/px-video.js
git diff --no-index css/px-video.css docs/css/px-video.css
```

which returns 0 differences. PR updated to include the css symlink.

**Comment by hozefaj** [comment]
@mreinstein After the PR merge...seeing the below 

```
The page build failed for the `master` branch with the following error:

The symbolic link `/css` targets a file which does not exist within your site's repository. For more information, see https://help.github.com/articles/page-build-failed-symlink-does-not-exist-within-your-site-s-repository/.

For information on troubleshooting Jekyll see: https://help.github.com/articles/troubleshooting-jekyll-builds
```

**Comment by mreinstein** [comment]
@hozefaj I removed the build step from `package.json` as it's not needed anymore. I guess we need to update jekyl to remove the call to this?

**Comment by mreinstein** [comment]
the symlinks definitely are in master. Can I see the jekyl config?

**Comment by hozefaj** [comment]
We are using github-pages to host the site. It must be using the default config that github provides.

**Comment by mreinstein** [comment]
hmm, ok. So it's not a jekyll configuration issue specific to this repo then. It seems Jekyll does _not_ support symlinks https://github.com/jekyll/jekyll/pull/315

I'm not sure how to fix this. I suppose we could revert...

**Comment by mreinstein** [comment]
so another option which I think would solve this: The actual `css/` and  `js/` directories could live in `docs/`, and them symlink that to the root directory. Since jekyll is looking in docs that would mean it won't see any symlinks, but the rest of the code would continue to function.

My only complaint with this is it's weird that the code would live in a folder named docs.
