### ISSUE TITLE
Installable via Bower and Component

### ISSUE THREAD

**Issue by paazmaya** [paypal/accessible-html5-video-player#19]
Please make this project available via Bower (http://bower.io/) and Component (http://componentjs.github.io/component.io/).

Perhaps even via `npm` ...

**Comment by bfred-it** [comment]
:+1: on `npm` support.

**Comment by weboverhauls** [comment]
Bower support appears to be added: 6eaa92710442ae2633e25bea2c223c3e2135d56c

**Comment by paazmaya** [comment]
Great!
Now it just needs to be published.

Component has been obsoleted.

How about `npm` support?

**Comment by hozefaj** [comment]
@paazmaya Updated `bower` version

**Comment by sunmd15** [comment]
Helllo

**Comment by hozefaj** [comment]
@weboverhauls Will look to see what it takes to create a npm module here. Thoughts?

**Comment by weboverhauls** [comment]
@hozefaj Thanks. I've fallen out of Node dev so I'll this up to you (and @mpnkhan).

**Comment by mpnkhan** [comment]
https://www.npmjs.com/package/accessible-html5-video-player
