### ISSUE TITLE
Caption is not working in google chrome

### ISSUE THREAD

**Issue by sksingh002** [paypal/accessible-html5-video-player#35]
Hi ,

We are using your accessibility video player and its was working fine, however in google chrome 43 , captioning stop working and its not displayed during video play.
Same issue on your demo URL (http://paypal.github.io/accessible-html5-video-player/
![video_caption](https://cloud.githubusercontent.com/assets/8165379/7807495/bbd93a6a-03a9-11e5-853d-42ec25054986.png)
) as well. Please take a look and let us know the solution for this.

**Comment by aboi** [comment]
Wow. Nice

**Comment by weboverhauls** [comment]
@sksingh002 Thanks for reporting. Hopefully I (or someone else) will have time to fix soon.
@aboi Really, WTF Chrome!

**Comment by weboverhauls** [comment]
Should be fixed. Please let me know if you experience problems with future versions of Chrome. This bug is a huge disappointment to me and blow to the progress of accessible HTML5 video.
