### ISSUE TITLE
Video embeding 

### ISSUE THREAD

**Issue by shtefcs** [paypal/accessible-html5-video-player#46]
Is there anyway to someone build feature so users can embed video player on other sites ? Like we emebed youtube videos for example.

Peace,

**Comment by hozefaj** [comment]
This repo does not host the videos. `youtube` hosts the video itself hence it can provide the embed link to use. This repo does not do that. It allows you to have a accessible controls around a hosted video.

You can probably do it by creating an simple HTML where you use this repo and then `iframe` it where ever you need. This is manual process for you. But I don't see this feature being added here. Thanks.
