### ISSUE TITLE
Captions are not working on Chrome latest

### ISSUE THREAD

**Issue by augbog** [paypal/accessible-html5-video-player#47]
http://paypal.github.io/accessible-html5-video-player/   

As of Chrome 44, I'm not seeing the captions appear in Chrome? I did some debugging and it works in other browsers.

For some reason even though it's passing the text correctly, `hasOwnProperty('text')` is returning `false`

    if (this.activeCues[0].hasOwnProperty("text")) {
        obj.captionsContainer.innerHTML = this.activeCues[0].text;
    }

**Comment by augbog** [comment]
After playing around, I'm still not sure why the `hasOwnProperty("text")` is failing but I changed the statement to this

    if (this.activeCues[0].hasOwnProperty("text") || this.activeCues[0].text !== "") {
        obj.captionsContainer.innerHTML = this.activeCues[0].text;
    }

And that seems to work. Not sure if there are some issues with this way of resolving.

**Comment by augbog** [comment]
After researching more, I believe this is due to the fact that Chrome now follows a new spec. See here:

https://developers.google.com/web/updates/2015/04/DOM-attributes-now-on-the-prototype

To quote the most relevant part

> Sometimes developers will use `hasOwnProperty` to check for presence of an property on an object. This will no longer work as per the spec because DOM attributes are now part of the prototype chain and `hasOwnProperty` only inspects the current objects to see if it is defined on it.

**Comment by weboverhauls** [comment]
@augbog Thanks so much!
