### ISSUE TITLE
IE 11 Issue on full screen view

### ISSUE THREAD

**Issue by tondesign** [paypal/accessible-html5-video-player#53]
The video player does'nt work well in IE11 Full screen view. The view size of the video doesnt change but stick to the right.

On IE inspect, the screen flickers a lot.

**Comment by nomadbakr** [comment]
Same problem on IE11. Fullscreen doesn't work as expected. 
Here is a link to screenshot: [http://downloads.nomaddesigns.ca/screenshots/2016-04-07_22-29-00.jpg](url)

**Comment by augbog** [comment]
Hey so given the merged PR above, can people test if this is still an issue? If not we should probably close.

**Comment by mreinstein** [comment]
I haven't tested this on master, but in my latest PR I've verified this is fixed: https://github.com/paypal/accessible-html5-video-player/pull/119

**Comment by hozefaj** [comment]
Tested on IE11. Issue is fixed now.
