### ISSUE TITLE
Uncaught TypeError: Cannot set property 'className' of undefined

### ISSUE THREAD

**Issue by FairHypo** [paypal/accessible-html5-video-player#58]
https://i.gyazo.com/c2a54eea2cdc7a6048a3329189d1654a.png
https://i.gyazo.com/2245b1e40d6be3345e54aa71a4b76a2f.png

Some stuff in the Console can be seen on the pictures

**Comment by weboverhauls** [comment]
[images referenced above show "undefined" error on "captionsContainer" object, line 521 of px-video.js using Chrome 47]

@FairHypo Thanks for reporting. I removed the Track element (caption file) but couldn't reproduce the error (on Chrome 46 nor 47). Would you confirm the error and provide more details such as specific steps to reproduce and code examples?

![image](https://cloud.githubusercontent.com/assets/473400/11671383/ef2f429e-9dd5-11e5-8b78-b2880f7464e1.png)
