### ISSUE TITLE
Resource interpreted as TextTrack but transferred with MIME type text/plain: "http://localhost:8080/OTX_server/accessiblehtml5videoplayer/media/captions_PayPal_Austin_en.vtt".

### ISSUE THREAD

**Issue by qinghechaoge** [paypal/accessible-html5-video-player#65]
Resource interpreted as TextTrack but transferred with MIME type text/plain: "http://localhost:8080/OTX_server/accessiblehtml5videoplayer/media/captions_PayPal_Austin_en.vtt".

console log  like this . how to fix it

**Comment by weboverhauls** [comment]
This is not an issue with this project but with your server. Add the vtt mime type to your server. More: http://stackoverflow.com/questions/15268604/html5-track-captions-not-showing

**Comment by weboverhauls** [comment]
More:
https://www.iandevlin.com/blog/2016/05/html5/help-with-webvtt
