### ISSUE TITLE
Responsive player dimensions

### ISSUE THREAD

**Issue by dripl** [paypal/accessible-html5-video-player#76]
This player as-is is not responsive. Javascript writes a fixed width in px to the wrapper div, and also to the video element when escaping from full-screen.
Ideally width should be 100% and height auto. Maximum width could be handled by CSS and/or wrapper elements.

**Comment by csiefer** [comment]
Can we start a video scaled to 100% initially?

**Comment by farskid** [comment]
@hozefaj I can fix this on demand :)

**Comment by weboverhauls** [comment]
FYI: Universal Video Player - a responsive player based off this player
source: https://source.ind.ie/project/video-player
article: https://ind.ie/blog/accessible-video-player/

**Comment by hozefaj** [comment]
@weboverhauls Would it make sense to port those changes here then?

**Comment by weboverhauls** [comment]
I believe so, yes.

**Comment by mreinstein** [comment]
The only complaint I have with the universal video player referenced above is it depends on flexbox. which isn't usable in pretty much any ie. I would love to see all the other changes backported in though. 

If I sent a PR with all changes except flexbox layout ,would it be welcome?

**Comment by hozefaj** [comment]
flex is pretty well supported https://caniuse.com/#search=flex. Also I don't think as an app we want to support anything older than ie 11.

**Comment by mreinstein** [comment]
it is well supported, but the project I'm maintaining is supporting all the way back to ie9. For me it's not an option. Perhaps a non-controversial compromise is I could port all the change _up to_ the flex stuff. That's the majority of the commits.

**Comment by mreinstein** [comment]
I would argue that if you don't want to support stuff older than ie11, there's not much point in using this repo; can pretty much use https://source.ind.ie/project/video-player directly.

**Comment by hozefaj** [comment]
We can use flexbox and if needed have a way to progressively degrade functionality for older browsers. Given the fact that usage of ie8 & ie9 is very low, feel its better to code for future than past.

**Comment by mreinstein** [comment]
I have a version running locally on my machine which takes everything (except for the license changes and branding) It's running here:

https://accessible-html5-video-player-ksagwqfhso.now.sh/docs/

If this looks right let me know and I'll send a PR.

**Comment by mreinstein** [comment]
this should be resolved now via https://github.com/paypal/accessible-html5-video-player/pull/119
