### ISSUE TITLE
Would it be possible to replace the sprite with Fontawesome icons.

### ISSUE THREAD

**Issue by Decrepidos** [paypal/accessible-html5-video-player#77]
This would make the controls more flexible.

**Comment by hozefaj** [comment]
@Decrepidos happy to accept a PR if you can make the changes

**Comment by Decrepidos** [comment]
Okay I did this on a project a while ago I'll dig it out and go from there. Thanks for the reply.

**Comment by weboverhauls** [comment]
Thank you for volunteering. SVG would actually be much better than font icons.
