### ISSUE TITLE
Error message for mp4 source under old browsers.

### ISSUE THREAD

**Issue by mihail-orpheus** [paypal/accessible-html5-video-player#79]
I have been testing the player under old firefox browsers and the video cannot be played in case mp4 source is used. I guess it is general html5 issue, but is there a way to generate an error message for these cases as firefox 10 for example can load html5 but not html5+mp4. 

How to handle this as the client will only use mp4 source videos? Thank you!

**Comment by weboverhauls** [comment]
Yes, this is a general HTML5 video question. Suggest trying OGG format and ensure the server mime types are set correctly.
https://support.mozilla.org/en-US/kb/html5-audio-and-video-firefox
https://support.mozilla.org/en-US/questions/916856
