### ISSUE TITLE
Closed Captions not working in IE or FF

### ISSUE THREAD

**Issue by johnsfleming** [paypal/accessible-html5-video-player#80]
I ran into difficulties getting the CC to work in IE or FF (so in cases where native captioning was not available and it fell back to the captioning code in the px-video.js file instead.

`req = xhr.responseText` would return the caption text

But the next line, `records = req.split('\n\n');` would not split the caption text at the double line breaks, so the records array would only have one element.  Then the whole array would get pushed into obj.captions, and then deleted when obj.captions.shift() was called.

I found that replacing the code to split the caption text with `records = req.split(/\r\n\r\n/);` and replacing the code to split the records array into individual caption chunks with `obj.captions[r] = record.split(/\r\n/);` solved the problem.

Not sure if this is a personal problem or something others might also run into trouble with.

**Comment by sniggitysnax** [comment]
I have seen the same thing @johnsfleming. It appears to be an issue with line endings in Windows vs. Unix. We have forced Unix line endings and it is working.
