### ISSUE TITLE
how to integrate with react?

### ISSUE THREAD

**Issue by jasan-s** [paypal/accessible-html5-video-player#83]

**Comment by hozefaj** [comment]
Currently there is no support for `react`. But this is something that needs to be worked on.

@mpnkhan @weboverhauls Can we plan to take this forward?

**Comment by farskid** [comment]
@hozefaj I'm actually working on the feature. Would be glad to send a PR.

**Comment by hozefaj** [comment]
@farskid Sure. please do. happy to review and merge.

**Comment by farskid** [comment]
@hozefaj Sent a PR for the topic on https://github.com/paypal/accessible-html5-video-player/pull/87
