### ISSUE TITLE
A flat badge for Paypal

### ISSUE THREAD

**Issue by aleen42** [paypal/accessible-html5-video-player#84]
Here is [a repository](https://github.com/aleen42/badges) for making badges more acceptable in documenting, and I hope that the flat badge can be used in documenting of such an awesome company.

[![paypal](https://rawgit.com/aleen42/badges/master/src/paypal.svg)](https://rawgit.com/aleen42/badges/master/src/paypal.svg)

**Comment by hozefaj** [comment]
Thanks. Using the badge in the Readme now(https://github.com/paypal/accessible-html5-video-player/commit/42e21395970d125512e46cfac6a4d0b7348c768a).
