### ISSUE TITLE
Article link broken on readme.md page

### ISSUE THREAD

**Issue by deque-dennis** [paypal/accessible-html5-video-player#93]
This link is broken on the readme:
Introducing an Accessible HTML5 Video Player 
https://www.paypal-engineering.com/2014/09/05/introducing-an-accessible-html5-video-player/

Is the PayPal Engineering blog its articles gone? Tried searching and couldn't find a new location.

If gone, suggest marking as such and adding this post:
https://paulschantz.com/2015/03/06/7-lessons-from-developing-an-accessible-html-5-video-player/

**Comment by hozefaj** [comment]
Sure. you want to send a PR with it?

@deque-dennis is this a new profile for you?

**Comment by deque-dennis** [comment]
So it's gone then, too bad.
I'll submit a PR soon. 
Yes, it's me (dennis/weboverhauls); I created this from my other account by mistake :-)

**Comment by weboverhauls** [comment]
It appears that the PayPal Engineering blog is back online.
