### ISSUE TITLE
React Demo link broken

### ISSUE THREAD

**Issue by weboverhauls** [paypal/accessible-html5-video-player#96]
Under "React Version" heading:
A demo could be reached at: **View Demo**

The link is:
http://paypal.github.io/accessible-html5-video-player/index.react.html

**Comment by hozefaj** [comment]
let me fix this

**Comment by weboverhauls** [comment]
@hozefaj React link is fixed, thanks. Looks like the captions are broken in this version though; the src value appears incorrect.

**Comment by farskid** [comment]
Captions are broken, it's getting 404.

**Comment by hozefaj** [comment]
@weboverhauls Check out the PR.
